feat: update labels on update merge request
un-ts/changesets-gitlab pull request #192
Opened 2024-10-05 08:09 UTC by Tchoupinax

Hello,

I am working with your tool and I want to update a merge request with labels but this feature is not available today, only at the creation.
This merge request aims to fix this.
It follows this work: https://github.com/un-ts/changesets-gitlab/pull/180/files

Thanks for your work!

2024-10-06 14:02 UTC, JounQin requested changes

2024-10-06 19:04 UTC, Tchoupinax reviewed
Review taken in account

2024-10-06 19:04 UTC, Tchoupinax commented on src/run.ts
> +      labels: getOptionalInput('labels')
Done!

2024-10-07 07:34 UTC, JounQin approved these changes

2024-10-07 07:37 UTC, merged

2024-10-07 07:38 UTC, JounQin commented
Thanks for your contribution!